build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/freedom-e-sdk_asm"
    - PLATFORMIO_PROJECT_DIR: "examples/freedom-e-sdk_dhrystone"
    - PLATFORMIO_PROJECT_DIR: "examples/freedom-e-sdk_gpio"
    - PLATFORMIO_PROJECT_DIR: "examples/freedom-e-sdk_hello"
    - PLATFORMIO_PROJECT_DIR: "examples/freedom-e-sdk_smp"
    - PLATFORMIO_PROJECT_DIR: "examples/native-blink_asm"

install:
- cmd: git submodule update --init --recursive
- cmd: SET PATH=%PATH%;C:\Python36\Scripts
- cmd: pip3 install -U https://github.com/platformio/platformio/archive/develop.zip
- cmd: platformio platform install file://.

test_script:
- cmd: platformio run -d %PLATFORMIO_PROJECT_DIR%

notifications:
  - provider: Slack
    incoming_webhook:
      secure: E9H0SU0Ju7WLDvgxsV8cs3J62T3nTTX7QkEjsczN0Sto/c9hWkVfhc5gGWUkxhlD975cokHByKGJIdwYwCewqOI+7BrcT8U+nlga4Uau7J8=
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
